/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_awen_jnitest_JNIUtil */

#ifndef _Included_com_awen_jnitest_JNIUtil
#define _Included_com_awen_jnitest_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_awen_jnitest_JNIUtil
 * Method:    initData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_awen_jnitest_JNIUtil_initData
  (JNIEnv *, jobject);

/*
 * Class:     com_awen_jnitest_JNIUtil
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_awen_jnitest_JNIUtil_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
