///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
//#ifdef __cplusplus
//extern "C" {
//#endif
//
///*
// * Class:     com_awen_jnitest_JNIUtil
// * Method:    initData
// * Signature: ()Ljava/lang/String;
// */
//jstring  Java_com_awen_jnitest_JNIUtil_initData(JNIEnv *env, jobject jObj){
//    return env->NewStringUTF("Hello NDK C++");
//}
///*
// * Class:     com_awen_jnitest_JNIUtil
// * Method:    getStringFromJni
// * Signature: ()Ljava/lang/String;
// */
//jstring  Java_com_awen_jnitest_JNIUtil_getStringFromJni
//        (JNIEnv *env, jobject jObj){
//    return env->NewStringUTF("笔沫拾光\nhttp://awenzeng.me/");
//}
//
//#ifdef __cplusplus
//}
//#endif